In [1]:
library(tibble)

In [2]:
create_df <- function() {
    df <- read.csv("fifo.csv", header = TRUE, sep = ",")
    #df$tally_q <- as.integer(df$tally_q)
    # df$sale <- as.integer(df$sale)
    # df$date <- as.Date(df$date, origin = "1899-12-30")

    df$cf_quan <- as.integer(rep(0, nrow(df)))
    df$cf_pps <- as.numeric(rep(0, nrow(df)))
    df$sell_quan <- as.integer(rep(0, nrow(df)))
    df$sell_price <- as.numeric(rep(0, nrow(df)))
    df$sell_proceeds <-as.numeric(rep(0, nrow(df)))
    df$profit_loss <- as.numeric(rep(0, nrow(df)))
    return(df)   # needed to return all the changes made to df
    }
df <- create_df()  # fct call

In [3]:
# When there is a pair of but/sell rows

buy_sell_easy1 <- function(df) {
   
    df <- df
    # allocate the unsold Buy quan (this will become a new row in df )
    unsold_carryforward <- buy_quan - sell_quan
    # sold_non_carryforward <- sell_quan - df_carryforward
    
    cat("\t\t", "top of buy_sell_easy1 fct with a passed value, i of :", i,  "\n")
    
    if(abs(sell_quan) == buy_quan) {
        sell_quan <- abs(df[i+1, 'quan'])
       
        
       cat("This will be a simple wash sale with no c/f", "\n")
       # one possibility of eliminating these rows is to zero the quans and set a flag
        # df[i, 'sell_q' ] <- sell_quan
        # df[i, 'sell_p'] <- df[i+1, 'pps'] * sell_quan
        # df[i +1, 'type'] <- "Sold"
        # df[i +1, 'index'] <- i
        # sell_quan <- 0
        # sell_index <- 0
        # cat("Clean sale. No C/F from sales condition type 1 ", "\n")
        return(df)       
        
    }
    
    else if(abs(sell_quan) > buy_quan) {
        sell_quan <- abs(df[i+1, 'quan'])       
        
        cat("This will be a simple wash sale with no c/f", "\n")
        return(df)
        }
         
    else if(abs(sell_quan) < buy_quan) {  
        
       
    #    sell_quan <- abs(df[i+1, 'quan'])
        cat("troublesome vars involving remaindes and carryforwards", "\n")
        
        # First things first, copy the "remainder" row 
        temp <- df[i, ]
        # Next, make changes (allocate the remainder values) to the new row before combining new row with df
              
            temp[i, 'type'] <- "Buy1"
            temp[i, 'quan'] <- unsold_carryforward
            temp[i, 'basis'] <- temp[i, 'pps'] * unsold_carryforward
        # Add the df, temp to the df        
        df <- add_row(df, temp, .before = i+1)
        # Next, make changes (allocate the remainder values) to the new row 
        df[i, 'type'] <- "SOLD"
        df[i, 'quan'] <- sell_quan 
        df[i, 'basis'] <- sell_quan * df[i, 'pps']
        df[i, 'tally_q'] <- sell_quan - sell_quan - unsold_carryforward
        df[i, 'tally_b'] <- df[i, 'tally_q'] * df[i, 'pps']
        df[i, 'cf_quan'] <- unsold_carryforward
        df[i, 'cf_pps'] <-  df[i, 'pps']
        df[i, 'sell_quan'] <- sell_quan
        df[i, 'sell_price'] <- sell_price
        df[i, 'profit_loss'] <- df[i, 'basis'] - sell_proceeds
        df[i, 'sell_proceeds'] <- sell_price * sell_quan
            
        
        
        
  #       df[i, 'sell_q' ] <- df[i, 'quan']
  #       df[i, 'sell_p'] <- df[i+1, 'pps'] * sell_quan
  #       df[i +1, 'type'] <- "Sold"
  # #      df[i, 'type'] <- "Sold"
  #       df[i +1, 'index'] <- i
  #       df[i, 'index'] <- i
  #       sell_quan <- 0
  #       # sell_index <- 0.
  #       cat("clean, no C/F from sales condition type 2 ", "\n")
        return(df)      
        
                
    
         
        # when the buys row i has quanity < sell quan, need carry values forward to next row,
         # And mo
       } else if(sell_ct - buy_ct == 0 && df[i, 'quan']  > df[i+1, 'quan'] ) {
        
        # fct call
        
        # Moved the code for this else if to fct().  Works
   #     df <- partial(df) 
        return(df)      
        }
     
        
        # new else if to deal with the Part Sold, aka carry forward
#          } else if (sell_ct - buy_ct == 1 ) {
        
#         cat("\n\n\n\n\n\n", "This is the else if for Part Sold. The value of i is: ", i, "\n\n\n\n\n\n")
        
#             # fct call 
#     #        df <- partial_cf(df, i)        
            
#         }
    
   # print(buys[i,])

    }  # fct

In [4]:
buy_sell_easy <- function(df) {
    
    cat("In buy_sell_easy fct.  Testing var seethru.  buy_quan and sell quan are: ", buy_quan, " and ", sell_quan, " buy_index and sell_index are: ", buy_index, " and ", sell_index, "\n")  
    df <- buy_sell_easy1(df)
    return(df)
    }
 buy_sell_advanced <- function(df) {
     df <- df
    cat("In buy_sell_Advanced fct.  buy_quan and sell quan are: ", buy_quan, " and ", sell_quan, " buy_index and sell_index are: ", buy_index, " and ", sell_index, "\n") 
     return(df)
    } 

buy_sell_partial <- function(df) {
    df <- df
    cat("In buy_sell_partial fct  buy_quan and sell quan are: ", buy_quan, " and ", sell_quan, " buy_index and sell_index are: ", buy_index, " and ", sell_index, "\n")  
    return(df)
    }
check_sell <- function(df) {
    df <- df
     cat("In check_sell fct buy_quan and sell quan are: ", buy_quan, " and ", sell_quan, " buy_index and sell_index are: ", buy_index, " and ", sell_index, "\n") 
    if(df[i+1, 'type'] == "Buy") {
        cat("The row number, ", i, "\n")
        return(df)
        }
    }

In [5]:
#  Move down the df from row to row 


df_sales <- data.frame()

for(i in 1:nrow(df[1:6,])) {   # hold to 6 itertions
    
    index_row <- i

    buy_quan <- df[i, 'quan']
    sell_quan <- df[i+1, 'quan']    
    buy_ct <- df[i, 'buy_ct']
    sell_ct <- df[i+1, 'buy_ct'] 
    buy_index <- df[i, 'index']
    sell_index <- df[i+1, 'index']
    sell_price <- df[i +1, 'pps']
    sell_proceeds <- sell_price * sell_quan
   
  
    
    
    

    cat("\n", "Loop row number is: ", i, "\n")
           

    if( df[i, 'type'] ==  "Buy") {

        cat("condition 1: ", df[i, 'type'], "\n")
        # simple buy/sell rows 
        if(df[i+1, 'type'] == "Sell") {
            df <- buy_sell_easy(df)
            
            #  Stacked Buy rows
            }else if (df[i+1, 'type'] == "Buy") {
                buy_sell_advanced(df) 
            }
     }else if (df[i, 'type'] == "Part Sell") {

        cat("condition 2: ", df[i, 'type'], "\n")
        buy_sell_partial(df)

    }else if ( df[i, 'type'] == "Sell") {

    # increment to next row from top of loop 

    cat("condition 3: ", df[i, 'type'], "\n")
        df <-check_sell(df)
        # return(df)


    } else {

        cat("condition 4 - Unrecognized type in row: ", i, " with 'type': ",  df[i, 'type'], "buy_quan and sell quan are: ", buy_quan, " and ", sell_quan, " buy_index and sell_index are: ", buy_index, " and ", sell_index, "\n") 
        }
 
 } # for

 Loop row number is:  1
condition 1:  Buy
In buy_sell_easy fct.  Testing var seethru.  buy_quan and sell quan are:  1050  and  1000  buy_index and sell_index are:  1  and  2
		 top of buy_sell_easy1 fct with a passed value, i of : 1
troublesome vars involving remaindes and carryforwards

 Loop row number is:  2
condition 4 - Unrecognized type in row:  2  with 'type':  Buy1 buy_quan and sell quan are:  50  and  1000  buy_index and sell_index are:  1  and  2

 Loop row number is:  3
condition 3:  Sell
In check_sell fct buy_quan and sell quan are:  1000  and  1000  buy_index and sell_index are:  2  and  3
The row number,  3

 Loop row number is:  4
condition 1:  Buy
In buy_sell_easy fct.  Testing var seethru.  buy_quan and sell quan are:  1000  and  1000  buy_index and sell_index are:  3  and  4
		 top of buy_sell_easy1 fct with a passed value, i of : 4
This will be a simple wash sale with no c/f

 Loop row number is:  5
condition 3:  Sell
In check_sell fct buy_quan and sell quan are:  1000  and  1000  buy_index and sell_index are:  4  and  5
The row number,  5

 Loop row number is:  6
condition 1:  Buy
In buy_sell_easy fct.  Testing var seethru.  buy_quan and sell quan are:  1000  and  1000  buy_index and sell_index are:  5  and  6
		 top of buy_sell_easy1 fct with a passed value, i of : 6
This will be a simple wash sale with no c/f

In [6]:
head(df, 10)

   index date  type buy_ct sell_ct co  quan pps     basis    tally_q tally_b
1  1     44926 SOLD 1      0       AMC 1000 4.07000  4070.00  -50     -203.50
2  1     44926 Buy1 1      0       AMC   50 4.07000   203.50 1050     4273.50
3  2     44953 Sell 1      1       AMC 1000 5.51240 -5512.40   50    -5512.40
4  3     44946 Buy  2      1       AMC 1000 5.62500  5625.00 1050     5625.00
5  4     44960 Sell 2      2       AMC 1000 6.68255 -6682.55   50    -6682.55
6  5     44949 Buy  3      2       AMC 1000 5.78800  5788.00 1050     5788.00
7  6     44960 Sell 3      3       AMC 1000 6.25500 -6255.00   50    -6255.00
8  7     44953 Buy  4      3       AMC 2000 5.23940 10478.80 2050    10478.80
9  8     44960 Sell 4      4       AMC 1000 6.19010 -6190.10 1050    -6190.10
10 9     44967 Buy  5      4       AMC 2000 4.74500  9490.00 3050     9490.00
   sale  cf_quan cf_pps sell_quan sell_price sell_proceeds profit_loss
1      0 50      4.07   1000      5.5124     5512.4        -1442.4
2      0  0      0.00      0      0.0000        0.0            0.0
3  -1000  0      0.00      0      0.0000        0.0            0.0
4      0  0      0.00      0      0.0000        0.0            0.0
5  -1000  0      0.00      0      0.0000        0.0            0.0
6      0  0      0.00      0      0.0000        0.0            0.0
7  -1000  0      0.00      0      0.0000        0.0            0.0
8      0  0      0.00      0      0.0000        0.0            0.0
9  -1000  0      0.00      0      0.0000        0.0            0.0
10     0  0      0.00      0      0.0000        0.0            0.0

In [7]:
temp

ERROR: Error in eval(expr, envir, enclos): object 'temp' not found

In [ ]:
temp <- df[2, ]
df <- add_row(df, temp, .before = 3)
head(df)
str(df)
tail(df)
nrow(df)

In [ ]:
head(df)